### ISSUE TITLE
Concern: Portal breaks by hand

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [ToroCraft/TeleToro#15]
Portals, both linked and unlinked, can be destroyed by punching them. It may be a problem when someone accidentally punches a linked portal that's 100,000 blocks away.
Can you make it so that the portal blocks can't be broken by the player directly like the nether portal but still be destroyed if the frame is broken or water bucket to the portal.

**Comment by frodare** [comment]
You are totally right. I thought you could punch the nether portals out, but that is only in creative.  Sure, I will make this change and release another version.

**Comment by frodare** [comment]
This is fixed in TeleToro 1.11.2-23, thx!

**Comment by TheGuyFromTheInternet** [comment]
Thanks. You really work fast. It's impressive.
