### ISSUE TITLE
Crashes if Lighting up Grass with Flint and Steel

### ISSUE THREAD

**Issue by Fundryi** [ToroCraft/TeleToro#18]
Crash: https://gist.github.com/Fundryi/2be6845b0178445d7d917f48ef64cb80
To be noted I don't know if it s a Biom O plenty bug or TeleToro.

**Comment by frodare** [comment]
This looks like an incompatibility between to the two mods, but caused by TeleToro not BOP.

https://github.com/ToroCraft/TeleToro/blob/master/java/net/torocraft/teletoro/blocks/BlockAbstractPortal.java#L426

Thanks for letting me know!

**Comment by Fundryi** [comment]
np hope this get fixed soon :)

**Comment by frodare** [comment]
Notes:
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.12.x-7.0.x/src/main/java/biomesoplenty/common/block/BlockBOPGrass.java#L139

**Comment by frodare** [comment]
@Fundryi if you get a chance, please try out TeleToro 1.12-26 and see if it fixed the problem, thanks again.
